<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace fredyns\region\models\base;

use Yii;

/**
 * This is the base-model class for table "rgn_area_lang".
 *
 * @property integer $id
 * @property integer $area_id
 * @property string $language
 * @property string $name
 * @property string $nickname
 *
 * @property \fredyns\region\models\Area $area
 * @property string $aliasModel
 */
abstract class AreaLang extends \yii\db\ActiveRecord
{
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'rgn_area_lang';
    }
    
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['area_id', 'name'], 'required'],
            [['area_id'], 'integer'],
            [['language'], 'string', 'max' => 16],
            [['name'], 'string', 'max' => 255],
            [['nickname'], 'string', 'max' => 32],
            [['area_id'], 'exist', 'skipOnError' => true, 'targetClass' => \fredyns\region\models\Area::className(), 'targetAttribute' => ['area_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'area_id' => 'Area',
            'language' => 'Language',
            'name' => 'Name',
            'nickname' => 'Nickname',
        ];
    }
        
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArea()
    {
        return $this->hasOne(\fredyns\region\models\Area::className(), ['id' => 'area_id']);
    }
                
}
