<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace fredyns\region\models\base;

use Yii;

/**
 * This is the base-model class for table "rgn_partCount".
 *
 * @property integer $id
 * @property integer $part_of
 * @property integer $type_id
 * @property integer $quantity
 *
 * @property \fredyns\region\models\Area $partOf
 * @property \fredyns\region\models\Type $type
 * @property string $aliasModel
 */
abstract class PartCount extends \yii\db\ActiveRecord
{
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'rgn_partCount';
    }
    
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['part_of', 'type_id', 'quantity'], 'integer'],
            [['type_id'], 'required'],
            [['part_of'], 'exist', 'skipOnError' => true, 'targetClass' => \fredyns\region\models\Area::className(), 'targetAttribute' => ['part_of' => 'id']],
            [['type_id'], 'exist', 'skipOnError' => true, 'targetClass' => \fredyns\region\models\Type::className(), 'targetAttribute' => ['type_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'part_of' => 'Part Of',
            'type_id' => 'Type',
            'quantity' => 'Quantity',
        ];
    }
        
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPartOf()
    {
        return $this->hasOne(\fredyns\region\models\Area::className(), ['id' => 'part_of']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getType()
    {
        return $this->hasOne(\fredyns\region\models\Type::className(), ['id' => 'type_id']);
    }
                
}
