<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace fredyns\region\models\base;

use Yii;

/**
 * This is the base-model class for table "rgn_type_lang".
 *
 * @property integer $id
 * @property integer $type_id
 * @property string $language
 * @property string $name
 *
 * @property \fredyns\region\models\Type $type
 * @property string $aliasModel
 */
abstract class TypeLang extends \yii\db\ActiveRecord
{
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'rgn_type_lang';
    }
    
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type_id', 'name'], 'required'],
            [['type_id'], 'integer'],
            [['language'], 'string', 'max' => 16],
            [['name'], 'string', 'max' => 255],
            [['type_id'], 'exist', 'skipOnError' => true, 'targetClass' => \fredyns\region\models\Type::className(), 'targetAttribute' => ['type_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type_id' => 'Type',
            'language' => 'Language',
            'name' => 'Name',
        ];
    }
        
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getType()
    {
        return $this->hasOne(\fredyns\region\models\Type::className(), ['id' => 'type_id']);
    }
                
}
